blank_issues_enabled: false
contact_links:
  - name: ❌ Help with Extensions
    url: https://sakayomi.sakayori.dev/docs/faq/browse/extensions
    about: For extension-related questions/issues
  - name: 🖥️ Sakayomi website
    url: https://sakayomi.sakayori.dev/
    about: Guides, troubleshooting, and answers to common questions
